#macro NETWORK_LOGIN 0
#macro NETWORK_PLAY 1

#macro LEFT_KEY 0
#macro RIGHT_KEY 1
#macro UP_KEY 2
#macro DOWN_KEY 3
#macro KEY_INTERACT 4
#macro KEY_SPELL1 5
#macro KEY_SPELL2 6
#macro KEY_SPELL3 7
#macro KEY_SPELL4 8


#macro KEY_CMD 0
#macro KEY_CMD_INTERACT 5
#macro KEY_ROT 3
#macro KEY_MOUSE 4
#macro NAME_CMD 1
#macro PING_CMD 2

#macro IS_KNIGHT 0
#macro IS_WIZARD 1

#macro OBJ_PLAYER 0
#macro OBJ_MONSTER 1
#macro OBJ_SPELL 2
#macro OBJ_ITEM 3

#macro RANK_NORMAL 0
#macro RANK_COMMUN 1
#macro RANK_RARE 2
#macro RANK_EPIC 3
#macro RANK_LEGENDARY 4

#macro CLIENT_ITEM_SHOW 0
#macro CLIENT_STEP_SHOW 1

#macro ITEM_TYPE_SWORD 0
#macro ITEM_TYPE_HELMET 1
#macro ITEM_TYPE_CHESTPLATE 2
#macro ITEM_TYPE_BOOT 3